name: fuelrush_ui
description: Shared Flutter UI components for FUELRUSH.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.47.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true