include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_dynamic_calls: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    require_trailing_commas: true
    unnecessary_lambdas: true
    use_named_constants: true